image: texlive/texlive:latest

LuaLaTeX:
    script:
        - apt-get update
        - apt-get install -y inkscape drawio
        - latexmk --shell-escape -pdflua ctufit-thesis.tex
    artifacts:
        paths:
            - ctufit-thesis.pdf
