image: texlive/texlive:latest

LuaLaTeX:
    script:
        - apt update
        - apt install -y inkscape xvfb

        - mkdir -p /opt
        - curl -L -o /opt/drawio.deb https://github.com/jgraph/drawio-desktop/releases/download/v26.2.2/drawio-amd64-26.2.2.deb

        - apt install -y /opt/drawio.deb

        - mv /usr/bin/drawio /usr/bin/drawio_
        - echo '#!/bin/bash' > /usr/bin/drawio
        - echo 'xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" drawio_ --no-sandbox "$@"' >> /usr/bin/drawio
        - chmod +x /usr/bin/drawio

        - latexmk --shell-escape -pdflua ctufit-thesis.tex
    artifacts:
        paths:
            - ctufit-thesis.pdf
